#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ToastBuddyLibExample.Ouya.Resource", IsApplication=true)]

namespace ToastBuddyLibExample.Ouya
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			FontBuddyLib.Ouya.Resource.Drawable.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Drawable.monoandroidsplash;
			FontBuddyLib.Ouya.Resource.Layout.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Layout.monoandroidsplash;
			FontBuddyLib.Ouya.Resource.String.library_name = ToastBuddyLibExample.Ouya.Resource.String.library_name;
			FontBuddyLib.Ouya.Resource.Style.Mono_Android_Theme_Splash = ToastBuddyLibExample.Ouya.Resource.Style.Mono_Android_Theme_Splash;
			HadoukInput.Ouya.Resource.Drawable.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Drawable.monoandroidsplash;
			HadoukInput.Ouya.Resource.Layout.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Layout.monoandroidsplash;
			HadoukInput.Ouya.Resource.String.library_name = ToastBuddyLibExample.Ouya.Resource.String.library_name;
			HadoukInput.Ouya.Resource.Style.Mono_Android_Theme_Splash = ToastBuddyLibExample.Ouya.Resource.Style.Mono_Android_Theme_Splash;
			ResolutionBuddy.Ouya.Resource.Drawable.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Drawable.monoandroidsplash;
			ResolutionBuddy.Ouya.Resource.Layout.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Layout.monoandroidsplash;
			ResolutionBuddy.Ouya.Resource.String.library_name = ToastBuddyLibExample.Ouya.Resource.String.library_name;
			ResolutionBuddy.Ouya.Resource.Style.Mono_Android_Theme_Splash = ToastBuddyLibExample.Ouya.Resource.Style.Mono_Android_Theme_Splash;
			ToastBuddyLib.Ouya.Resource.Drawable.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Drawable.monoandroidsplash;
			ToastBuddyLib.Ouya.Resource.Layout.monoandroidsplash = ToastBuddyLibExample.Ouya.Resource.Layout.monoandroidsplash;
			ToastBuddyLib.Ouya.Resource.String.library_name = ToastBuddyLibExample.Ouya.Resource.String.library_name;
			ToastBuddyLib.Ouya.Resource.Style.Mono_Android_Theme_Splash = ToastBuddyLibExample.Ouya.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Splash = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int monoandroidsplash = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Splash = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
